### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by jlqzzz** [Pang-Yatian/Point-MAE#10]
Thank you for your outstanding work!

Does the Input, Masking and Reconstruction in the visualization result correspond to the point cloud in gt.txt, vis.txt and dense_points.txt respectively?

If so, why does the reconstructed point cloud have many more points than the original point cloud? Shouldn't it be nearly equal?

I look forward to your reply!

**Comment by jlqzzz** [comment]
> Hi,
> 
> Yes. The reconstruction point cloud has about 2x points compared to the original input. It is caused by 1). The input point cloud with 1024 points is divided into 64 patches * 32 points. The point patches may OVERLAP. 2). Then, for reconstruction, we also predict 64 * 32 points.
> 
> Hope that answers your question.

I get it! Thank you for your timely reply!

**Comment by Pang-Yatian** [comment]
You are most welcome!
