### ISSUE TITLE
Confusion about the masking strategy and prediction target

### ISSUE THREAD

**Issue by auniquesun** [Pang-Yatian/Point-MAE#11]
@Pang-Yatian Thanks for sharing the paper and code.

Two points I am confused with are as follows.

1. About the masking strategy. After FPS and kNN, there are overlapped points in different patches (64*32 > 1024). When a patch overlapping with a visible patch is masked, it means all points in this masked patch are invisible to the encoder, but at the same time, in the visible patch there are visible points overlapped with ones in the masked patch, which means the masked points in the masked patch are visible to the encoder. Is it information leakage? How do you handle this case in the masking strategy?

2. About the prediction target. Following the above question, when a masked patch overlaps with a visible patch, does the prediction target still predict same number of points for all masked patches, regardless of there exist visible points overlapping with those in masked patches?

**Comment by Pang-Yatian** [comment]
Feel free to reopen it if you have more questions.

**Comment by auniquesun** [comment]
> Hi,
> 
> 1. Basically, a set of points may belong to masked patches and visible patches at the same time. I would say this is not an information leakage, as we mask and reconstruct the whole point cloud in patchwise. Although to some extent, the overlap of points makes the reconstruction task easier. A large masking ratio (60% - 80%) is helpful to deal with this issue.
> 2. Yes. Your understanding is correct.

Thanks for you reply.

For case 1, since some parts of prediction targets are included in the input, maybe it's hard to let readers buy the idea it is not an information leakage. But dividing point patches to feed Transformer is a reasonalbe way.
