### ISSUE TITLE
What do OBJ-BG and OBJ-ONLY mean?

### ISSUE THREAD

**Issue by charlesCXK** [Pang-Yatian/Point-MAE#12]
Dear author:
In your paper, the results for OBJ-BG and OBJ-ONLY are 88.29 and 90.01, respectively. However, in your repo, the results are 90.02 and 88.29. Do the numbers in the paper be put in the wrong places?

**Comment by Pang-Yatian** [comment]
Hi,

Please refer to the latest version of our paper, in which the result is consistent with our repo.

OBJ-BG variant means objects are placed in a background, while OBJ-ONLY only has the object.

**Comment by charlesCXK** [comment]
Thanks for your quick reply! I still have a question: usually, the performance on OBJ-ONLY is higher than the performance on OBJ-BG, while Point-MAE shows different properties. May I ask if you have any thoughts on this phenomenon?

**Comment by Pang-Yatian** [comment]
Hi,

Actually, we also find this property but have no clues yet. We are doing more experiments. 

We would also be happy to discuss if you could provide some thoughts.

**Comment by charlesCXK** [comment]
I have no idea yet. Thanks for sharing the code and answering the question!

**Comment by Pang-Yatian** [comment]
You are most welcome. We will update if there is any new finding on this property.
