### ISSUE TITLE
A question about ShapeNet "train.txt" and "test.txt"

### ISSUE THREAD

**Issue by QWTforGithub** [Pang-Yatian/Point-MAE#13]
Thank you very much for your well-organized code.  I want to train the pre-trained model on ShapeNet-55, but I can't find the train.txt and test.txt of Shapenet-55. Where are they?

**Comment by Pang-Yatian** [comment]
Hi,

Sorry for the confusion.

They are [here](https://github.com/lulutang0608/Point-BERT/tree/49e2c7407d351ce8fe65764bbddd5d9c0e0a4c52/data/ShapeNet55-34/ShapeNet-55).

**Comment by QWTforGithub** [comment]
> Hi,
> 
> Sorry for the confusion.
> 
> They are [here](https://github.com/lulutang0608/Point-BERT/tree/49e2c7407d351ce8fe65764bbddd5d9c0e0a4c52/data/ShapeNet55-34/ShapeNet-55).

Thank you!

**Comment by Pang-Yatian** [comment]
You are welcome.
