### ISSUE TITLE
How to test on ScanObjectNN?

### ISSUE THREAD

**Issue by Phoebe-ovo** [Pang-Yatian/Point-MAE#16]
What's the command for testing on ScanObjectNN?
Whether it uses voting?

**Comment by Pang-Yatian** [comment]
Hi,

```
CUDA_VISIBLE_DEVICES=<GPUs> python main.py --test --config cfgs/finetune_scan_hardest.yaml \
--exp_name <output_file_name> --ckpts <path/to/best/fine-tuned/model>
```
Note that this command includes voting. 

But we do NOT use the results with voting as stated in the paper. We directly use the testing result during training.
