### ISSUE TITLE
not able to import "chamfer"

### ISSUE THREAD

**Issue by krmayankb** [Pang-Yatian/Point-MAE#17]
after running: 
`%cd /content/drive/MyDrive/Research/Point-MAE/GitHub/Point-MAE/extensions/chamfer_dist`
`!python setup.py install --user` 

I get this: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/91506057/171694849-0650407d-afca-4c19-9589-0d537da66d31.png">

but when I try to import chamfer it does not work. One possible reason could be it is not installing chamfer because it stops at the resolving dependencies. Is there something that I am missing here? 

<img width="628" alt="image" src="https://user-images.githubusercontent.com/91506057/171695016-4ff3550d-a3f7-4bdf-a827-c327ba65f657.png">

tried multiple work-around but couldn't solve it. Can you please help?

**Comment by Pang-Yatian** [comment]
Hi,

Please try to add the path (/root/.local/lib/python3.7/site-packages) of the installed packages into $PYTHONPATH.

[Reference](https://github.com/lulutang0608/Point-BERT/issues/33#issuecomment-1098924945)

**Comment by krmayankb** [comment]
Hi, Thanks for your reply, I tried adding directory to the path but I am still facing the same problem. 

<img width="655" alt="image" src="https://user-images.githubusercontent.com/91506057/171805953-214bf72d-2503-4844-b2de-b79b31ec00ed.png">

I checked the location for the files. Files are available but the import is still not working.  
<img width="652" alt="image" src="https://user-images.githubusercontent.com/91506057/171806166-a2bebe7e-0405-4710-a62b-f21c16d8a967.png">

**Comment by Pang-Yatian** [comment]
Hi,

Did you use a virtual environment?

**Comment by krmayankb** [comment]
Hi, I am using google colab to run the code.

**Comment by Pang-Yatian** [comment]
Sorry, I am not familiar with colab. 

We did not meet this issue in anaconda environments or docker images.

**Comment by Pang-Yatian** [comment]
Sorry, I am not familiar with colab.

We did not meet this issue in conda environments or docker images.

**Comment by saharahmadisohraviyeh** [comment]
> after running: `%cd /content/drive/MyDrive/Research/Point-MAE/GitHub/Point-MAE/extensions/chamfer_dist` `!python setup.py install --user`
> 
> I get this: <img alt="image" width="683" src="https://user-images.githubusercontent.com/91506057/171694849-0650407d-afca-4c19-9589-0d537da66d31.png">
> 
> but when I try to import chamfer it does not work. One possible reason could be it is not installing chamfer because it stops at the resolving dependencies. Is there something that I am missing here?
> 
> <img alt="image" width="628" src="https://user-images.githubusercontent.com/91506057/171695016-4ff3550d-a3f7-4bdf-a827-c327ba65f657.png">
> 
> tried multiple work-around but couldn't solve it. Can you please help?

Hi, did you solve this problem?
I'm using colab for this code and I have the same issue, can you help me? :(

**Comment by krmayankb** [comment]
Hi, My project direction got changed. But I was not able to solve it when I was working with this. You can try working with conda environment as suggested earlier.

**Comment by krmayankb** [comment]
Hi, My project direction got changed. But I was not able to solve it when I was working with this. You can try working with conda environment as suggested earlier. 

> > after running: `%cd /content/drive/MyDrive/Research/Point-MAE/GitHub/Point-MAE/extensions/chamfer_dist` `!python setup.py install --user`
> > I get this: <img alt="image" width="683" src="https://user-images.githubusercontent.com/91506057/171694849-0650407d-afca-4c19-9589-0d537da66d31.png">
> > but when I try to import chamfer it does not work. One possible reason could be it is not installing chamfer because it stops at the resolving dependencies. Is there something that I am missing here?
> > <img alt="image" width="628" src="https://user-images.githubusercontent.com/91506057/171695016-4ff3550d-a3f7-4bdf-a827-c327ba65f657.png">
> > tried multiple work-around but couldn't solve it. Can you please help?
> 
> Hi, did you solve this problem? I'm using colab for this code and I have the same issue, can you help me? :(

**Comment by saharahmadisohraviyeh** [comment]
Hi, I changed the versions of Torch and Torch Vision. After you have installed the requirements.txt please install this code in colab:

!pip install torch==1.7.0 torchvision torchaudio torchtext --extra-index-url https://download.pytorch.org/whl/cu113
Good luck
 
    On Sunday, February 26, 2023 at 05:33:25 AM GMT+3:30, Mayank Kumar ***@***.***> wrote:  
 
 


Hi, My project direction got changed. But I was not able to solve it when I was working with this. You can try working with conda environment as suggested earlier.



after running: %cd /content/drive/MyDrive/Research/Point-MAE/GitHub/Point-MAE/extensions/chamfer_dist !python setup.py install --user
I get this: 
but when I try to import chamfer it does not work. One possible reason could be it is not installing chamfer because it stops at the resolving dependencies. Is there something that I am missing here?

tried multiple work-around but couldn't solve it. Can you please help?


Hi, did you solve this problem? I'm using colab for this code and I have the same issue, can you help me? :(
