### ISSUE TITLE
Questions about Transformer achitecture ?

### ISSUE THREAD

**Issue by zhulf0804** [Pang-Yatian/Point-MAE#21]
Thanks for your nice work. I have two questions about Transformer achitecture (or name):

(1) As mentioned  in the paper, your method is based on standard Transformer. My understanding is that your method is `just` based on standard `Transformer encoder` without standard `Transformer decoder`. Is it right ?

(2) In your open source code, the classification network is defined as PointTransformer as follows. In fact, it's different from [T]PointTransformer reported in your paper. Is it right ?
https://github.com/Pang-Yatian/Point-MAE/blob/fd5a476408220b4b31032eee62b5e89d051481a2/models/Point_MAE.py#L421-L424

Looking forward to your reply.

**Comment by Pang-Yatian** [comment]
Hi,

1. Yes.

2. Sorry for the confusion. Yes, it is just a name. [T]PointTransformer does not use standard Transformer.

**Comment by zhulf0804** [comment]
Thanks for your reply.
