### ISSUE TITLE
How to open TFBoard file

### ISSUE THREAD

**Issue by zzwj66** [Pang-Yatian/Point-MAE#22]
After runing few shotting learning, there are some files in ./experiments/fewshot/cfgs/TFBoard/out_x_x. From its name I think it is tfevent file, but  I can't open it by TensorBoard, by the way, I don't know thy it is .amax form. So, how can I open it?

**Comment by Pang-Yatian** [comment]
Hi,

As there may be many tfevent files in /TFBoard, you may need to move a single tfevent file into a sub-directory and load the sub-directory.  

For example,

```
mkdir test
mv events.out.tfevents.1644662571.Longshot ./test/

tensorboard --logdir="./test"
```

.amax would not be a problem.
