### ISSUE TITLE
How to change embedding module output size?

### ISSUE THREAD

**Issue by DanieleMenchetti** [Pang-Yatian/Point-MAE#24]
Hi, thank you for your work on point clouds.
Could I ask you how to change the embedding module output size?
I set encoder_dims and transf_dim to 512, but I'm getting a shape error on attention class (image below).
Is there anything else that I should edit?

![error](https://user-images.githubusercontent.com/39400348/187388051-0266fe54-b444-47b0-aad3-46d6240ab944.PNG)

Looking for your reply,
Daniele

**Comment by Pang-Yatian** [comment]
Hi,

It is caused by the multi-head attention mechanism. 512/6=85.3333, 512//6 = 85. You may need to make sure dim can be divided by num-heads.

**Comment by DanieleMenchetti** [comment]
> Hi,
> 
> It is caused by the multi-head attention mechanism. 512/6=85.3333, 512//6 = 85. You may need to make sure dim can be divided by num-heads.

Thank you so much!
