### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by josenachorr** [Pang-Yatian/Point-MAE#25]
Hi, I want to try your model in our dataset, but I have not been able to install pointnet2_ops whatshoever. I was wondering if you had a docker image or a complete and functional conda environment that you could share in order to use your method.
Thanks a lot

**Comment by wangsenchen** [comment]
> 

I have encountered the same problem. Have you solved it

**Comment by Pang-Yatian** [comment]
Please follow their repo to install it correctly.
