### ISSUE TITLE
Configuration files for finetuning

### ISSUE THREAD

**Issue by ivansipiran** [Pang-Yatian/Point-MAE#26]
Hi! thanks for the very nice work. I succesfully pre-train the network with ShapeNet. However, when I try to finetune the model with other datasets, the configuration files are wrong.

The configuration files uses PointTransformer as model. When I try to change the model by Point-MAE, the finetuning stops with an error to compute the accuracy. Please can you provide the way to perform the finetuning? 

Thanks in advance.
Bests

**Comment by Pang-Yatian** [comment]
We have provided the correct finetuning scripts on modelnet40 and scanobjnn.

**Comment by Pari0511** [comment]
Hi, 
but i am getting error while fine-tuning on objbg and objonly. 
error something like:
return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported.
