### ISSUE TITLE
The result cannot be reproduced on ScanObjectNN_hardest, ScanObjectNN_objectbg, and ShapeNetPart. 

### ISSUE THREAD

**Issue by Daybreak-Zheng** [Pang-Yatian/Point-MAE#27]
The result cannot be reproduced on ScanObjectNN_hardest, ScanObjectNN_objectbg, and ShapeNetPart. Can you provide more detailed superparameters, such as setting random seeds? Our experiment was reproduced on 3090.

**Comment by Pang-Yatian** [comment]
Hi,

We did not set random seeds purposely. Please refer to the [logs and models](https://github.com/Pang-Yatian/Point-MAE/releases/tag/main) for details.

**Comment by Daybreak-Zheng** [comment]
How do I get the results of a few shots? I can get the best results for 10 times on different.pkl data sets. How do I finally calculate the results of a few shots? For example, how to calculate 5way_10shot?

**Comment by Pang-Yatian** [comment]
Just calculate mean and std.
