### ISSUE TITLE
The command of finetune on modelnet

### ISSUE THREAD

**Issue by whuhxb** [Pang-Yatian/Point-MAE#29]
Hi @kabouzeid @yuanli2333 @Pang-Yatian 

The full command of finetune on modelnet is shown as:
CUDA_VISIBLE_DEVICES=<GPUs> python main.py --config cfgs/finetune_modelnet.yaml \
--finetune_model --exp_name <output_file_name> --ckpts <path/to/pre-trained/model>

How to set --finetune_model here? Thanks a lot.

**Comment by Pang-Yatian** [comment]
hi,

it is a "store_true" arg. no need to pass anything.
