### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by arndz** [Pang-Yatian/Point-MAE#35]
Hi,

thank you for this great repository!

I have two questions regarding the patches: 
1. Are the number of patches and points per patch always chosen by hand or are they dynamic w.r.t the size of the input point cloud?

2. Did you also observed predictions (maybe depending on the patch size) on which most points are located at the center of the patch?

Thank you !

**Comment by Pang-Yatian** [comment]
Hi,

1. In our work, the number of patches is dynamic based on the input points. The points number per patch is fixed. Our solution may not be optimal. You may try different settings.

2. We did not observe that. As we use chamfer distance loss, this situation should not happen theoretically.
