### ISSUE TITLE
About the scale factor 

### ISSUE THREAD

**Issue by martianxiu** [Pang-Yatian/Point-MAE#36]
Hi Yatian, 

Thanks for sharing the code. 
About the comment in L106 (the code below), how should I set the scale factor manually so that I can use your pretrained model?   
https://github.com/Pang-Yatian/Point-MAE/blob/11f4c99f60e2f635e40d23ccaf21ec9aa42705ef/models/Point_MAE.py#L101-L108

**Comment by Pang-Yatian** [comment]
Hi,

No need to set this factor. We follow the standard transformer setting.
