### ISSUE TITLE
How to distribute data parallel training the code

### ISSUE THREAD

**Issue by Chopper-233** [Pang-Yatian/Point-MAE#38]
I'm trying to train your code in my linux system.My command is CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_pec_node=4 main.py --config ./cfgs/pretrain.yaml --launcher pytorch
I'm wondering whether it's right or not

**Comment by Pang-Yatian** [comment]
yes, it is correct.
