### ISSUE TITLE
So Many Fine-Tuning Epochs

### ISSUE THREAD

**Issue by aka100kvolt** [Pang-Yatian/Point-MAE#4]
Thanks for open-sourcing your work.

I notice that you pre-train on ShapeNet for 300 epochs and then fine-tune for another 300 epochs. I wonder why your model needs so many epochs for fine-tuning? Can you provide some results for the intermediate epochs? Because some works do not even need that many epochs for training from scratch. It is better to disentangle the improvements from training strategies like training epochs. Thanks.

**Comment by Pang-Yatian** [comment]
Hi,

Training or finetuning for around 300 epochs is normal. For example, SOTA Point-MLP also trains the model for 300 epochs. For fair comparisons, we follow the previous works Point-BERT pre-train 300 epochs and fine-tune 300 epochs. Fine-tuning performance may drop a little bit for fewer epochs. We will update a new result on ScanObjectNN later.

**Comment by Pang-Yatian** [comment]
We have updated fine-tune performance for 300 epochs on ScanObjectNN. The OA is 85.18%, higher than 84.52% when fine-tuning for 200 epochs.

**Comment by aka100kvolt** [comment]
Thank you for your explanation and updated results!
