### ISSUE TITLE
Install emd extension with torch>1.11.0

### ISSUE THREAD

**Issue by lqxisok** [Pang-Yatian/Point-MAE#42]
1. `extensions/emd/cuda/emd_kernel.cu` 
    - comment `#include <THC/THC.h>`
    - replace all `CHECK_EQ` to `TORCH_CHECK_EQ`
    - replace all `THCudaCheck` to `AT_CUDA_CHECK`

**Comment by X-Bruce-Y** [comment]
life saver, man

**Comment by lz0728** [comment]
> 1. `extensions/emd/cuda/emd_kernel.cu`
>    
>    * comment `#include <THC/THC.h>`
>    * replace all `CHECK_EQ` to `TORCH_CHECK_EQ`
>    * replace all `THCudaCheck` to `AT_CUDA_CHECK`

Hello, what does this mean
