### ISSUE TITLE
ModelNet(8k) accuracy of 1024 PCs

### ISSUE THREAD

**Issue by Harr7y** [Pang-Yatian/Point-MAE#45]
Hi, I test the accuracy of the finetuning ModelNet40(8k) checkpoint on 1024 points, and the result shows that the accuracy is about 68.52% without voting. I am curious if the model's after the finetuning with 8k PCs is only suitable for the case of 8k PC input?

Model: ModelNet40 (8k)
Input : 1024 PCs  ->  Accuracy: 68.52%
Input : 8192 PCs  ->  Accuracy: 93.40%

The number of points is changed through **N_POINTS** in ModelNet40.yaml

Or is this something wrong with my command:
command: python main.py --config cfgs/finetune_modelnet_8k.yaml --test --exp_name test --ckpts /Point-MAE/checkpoint/modelnet_8k.pth

**Comment by Pang-Yatian** [comment]
Yes, it is normal. We also tested this finetune pipeline before and found similar results. I guess the point cloud density is different from the image resolution, so this way cannot work.

**Comment by Harr7y** [comment]
Thanks for your reply.  :)
