### ISSUE TITLE
About pos_emd and attention distribution

### ISSUE THREAD

**Issue by JiaweiMao12135** [Pang-Yatian/Point-MAE#52]
I used your code for training a pre-train model on my data (8192 points for each sample).After training(Group number:512; Group Size:32, mask ratio:0.6, encoder dim: 384), the reconstruction of my test data seems well. But when I check the encoder output, position embeddings and attn (attention blocks output) to find out which groups are important for reconstruction process, the position embeddings of different groups  in a sample are almost same, it makes me confused. Even the attn values of different gropss are almost average (=1/512). The interpretability is so important for me, can you offer me some suggestions? thank you.

**Comment by Pang-Yatian** [comment]
Hi, 

Honestly, I did not conduct similar experiments before. I have no clues at this time. Sorry about that.
