### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Research-Code-123** [Pang-Yatian/Point-MAE#54]
Dear author:

Have you ever met this error?

 chamfer_dist]$ python setup.py install --user
running install
/public/home/hpc220270/anaconda3/envs/pointmae/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/public/home/hpc220270/anaconda3/envs/pointmae/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating chamfer.egg-info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
writing manifest file 'chamfer.egg-info/SOURCES.txt'
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
error: [Errno 2] No such file or directory: 'which'

Thanks

**Comment by Pang-Yatian** [comment]
Hi, it seems like an error related to the external package. I think you should check your environment. We have tested on 3090s/V100s and everything works fine.

**Comment by Pang-Yatian** [comment]
I guess it may be caused by the CUDA version. Please try to downgrade your CUDA version and try again. Another way is to use another PyTorch package, such as https://github.com/krrish94/chamferdist, to replace this one.
