### ISSUE TITLE
About sample strategy during pretrain 

### ISSUE THREAD

**Issue by JiaweiMao12135** [Pang-Yatian/Point-MAE#55]
In your paper, regarding the sampling strategy in the pre-training phase, you mention that ‘for each instance, we sampled 1024 points by FPS as the input point cloud’. But in your code (ShapeNet55Dataset.py line 64), the sampling seems to be random. Therefore, I just want to know which sampling strategy is the right one in the pre-training phase.
```
data = IO.get(os.path.join(self.pc_path, sample['file_path'])).astype(np.float32)
        data = self.random_sample(data, self.sample_points_num)
        data = self.pc_norm(data)
```

**Comment by Pang-Yatian** [comment]
Hi, thanks a lot for pointing out this typo. We use the strategy as the open-sourced code does, which is actually random sampling.
