### ISSUE TITLE
ShapeNetPart dataset

### ISSUE THREAD

**Issue by ywyue** [Pang-Yatian/Point-MAE#56]
Hi @Pang-Yatian, thank you for the great work! The link for ShapeNetPart dataset is not working: https://shapenet.cs.stanford.edu/media/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip

Could you please share the data if you have a copy? Thank you in advance!

**Comment by ywyue** [comment]
For people who have the same issue: the [PointCloudMamba](https://github.com/SkyworkAI/PointCloudMamba/tree/main/data) repo contains a GoogleDrive [link](https://drive.google.com/uc?id=1W3SEE-dY1sxvlECcOwWSDYemwHEUbJIS) to download the data.

**Comment by Pang-Yatian** [comment]
@ywyue Hi, thanks for the information.
