### ISSUE TITLE
Pre-training Log

### ISSUE THREAD

**Issue by Hiusam** [Pang-Yatian/Point-MAE#8]
Hi, thanks for your great job!
Could you please provide the pre-training log so I can check whether my training works correctly? Thanks!

**Comment by Pang-Yatian** [comment]
Hi,

Thanks for your interest.

We have provided our logs and pre-trained models [here](https://github.com/Pang-Yatian/Point-MAE/releases).

**Comment by Hiusam** [comment]
Thanks!
