### ISSUE TITLE
What is the difference between point cloud completion task and point cloud masked reconstruction?

### ISSUE THREAD

**Issue by jlqzzz** [Pang-Yatian/Point-MAE#9]
First of all, thank you for your outstanding work!

The pretext task used in your pre-training phase is point cloud masked reconstruction. 

I wonder what's the difference between point cloud completion task and point cloud masked reconstruction?

**Comment by Pang-Yatian** [comment]
Hi,

I would say that in our pre-text task, the masked point patches still have their centers' position. However in point cloud completion task, we have no information about the missing part, which is a more difficult task.

**Comment by jlqzzz** [comment]
> Hi,
> 
> I would say that in our pre-text task, the masked point patches still have the information of their centers' position. However in point cloud completion task, we have no information about the missing part, which is a more difficult task.

I get it! Thank you!
